lightning/config/config.go, lightning/restore/restore.go, lightning/worker/worker.go, tidb-lightning.toml
Limit closed engine count for coordinating `write` and `import`
Apply a worker before call `engine.Close()` and release worker after `engine.Cleanup`
Tests 
Code changes
Side effects
=> Limit closed engine count for coordinating `write` and `import`

cmd/tidb-lightning-ctl/main.go, lightning/kv/importer.go
This is mainly intended for speeding up debugging tikv-importer's import step by entirely skipping the "write" step.
Expose tikv-importer's `ImportEngine` and `CleanupEngine` APIs to `tidb-lightning-ctl`.
Tests 
* 
Side effects
=> tidb-lightning-ctl: added --import-engine and --cleanup-engine commands

cmd/tidb-lightning-ctl/main.go
fix error
```bash
cmd/tidb-lightning-ctl/main.go:257:40: cannot use engineID (type int) as type int32 in argument to importer.UnsafeCloseEngine
```
add type cast
Tests 
- Unit test
=> *: parameter type fix

tests/run.sh
currently cleanup script in integration test does not work, if developer wants to re-run integration test in his/her local environment, he/she has to clean /tmp/lightning_test_result manually
fix cleanup scripts
Tests 
- run integration test in local environment multiple times
=> test: fix cleanup script to enable re-run integration test locally

lightning/common/util.go, lightning/mydump/csv_parser.go, lightning/restore/restore.go
Test `checkpoint_error_destroy` in integration got error randomly, both in local environment and JenkinsCI.
Lightning could exit before all checkpoints are saved, as the `WaitGroup` is not always 
added before this line https://github.com/pingcap/tidb-lightning/blob/master/lightning/restore/restore.go#L204 returns
1. After `RestoreController.Run` is returned, no more messages will be sent to `rc.saveCpCh`, so we can close it safely and ensure all `saveCp` are consumed
2. remove some unused code
Tests 
=> checkpoint: fix checkpoint not updated in some scenario

lightning/restore/restore.go
Add local checksum information, which helps us to compare checksum manually when executing `ADMIN CHECKSUM TABLE table_name` timeout.
Add some logs.
Tests 
Side effects
N/A
N/A
=> restore: add local checksum log

lightning/common/util.go, lightning/restore/restore.go, tests/checkpoint_chunks/run.sh
add test case to cover lightning is killed durning data import
use gofail to control lightning to kill itself after one chunk is imported
Tests 
=> tests: add kill lightning test in checkpoint_chunks case

lightning/restore/restore.go, tests/checkpoint_chunks/run.sh
Fix this failure https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/test_lightning_master/detail/test_lightning_master/25/pipeline
Problem was that #158 introduced a new test involving a failpoint which definition is changed in #145. There is no syntactical conflict between the two so the PRs merged cleanly, but the semantic conflict caused the integration test failure above.
Updated the failpoint definition.
Tests 
Side effects
=> tests: fix a test failure due to conflict between #145 and #158

lightning/metric/metric.go, lightning/mydump/loader.go, lightning/restore/restore.go
Put the large table in the front of the slice which can avoid large table take a long time to import and block small table to release index worker.
Sorting tables before restore.
Tests 
- Unit test
Side effects
N/A
N/A
=> restore: give priority to small tables for importing

go.mod, go.sum
The recent update to failpoint breaks the old runtime.
As we didn't pin the failpoint tool, we need to instead update the failpoint dependency to fix the breakage.
Tests 
- No code
Side effects
=> [2.1] go.mod: update failpoint dependency to fix integration test failure

cmd/tidb-lightning/main.go, go.mod, go.sum
We need to sync the logger before exit. https://godoc.org/go.uber.org/zap#Logger.Sync
Added a call to `Sync()`, modeled after TiDB https://github.com/pingcap/tidb/blob/b864fac504f9f059a39a7d477e923440f6d88a55/tidb-server/main.go#L176-L182.
Also, updated failpoint deps, see pingcap/dm#122.
Tests 
* `make` works
Side effects
=> main: sync log before exit + update failpoint dep

lightning/config/config.go, tidb-lightning.toml
The current default table-concurrency is 8, meaning up to 8 data engines will be opened. Then the default index-concurrency is 2, so together up to 10 engines will be opened. But Importer's default max-open-engine is 8, so with the default settings we will hit the TooManyOpenEngines error.
Reduce the default table-concurrency to 6.
Tests 
- No code
Side effects
=> config: reduce default table-concurrency from 8 to 6

lightning/config/config.go, lightning/restore/checkreq_test.go, lightning/restore/restore.go, lightning/restore/restore_test.go, lightning/restore/testlogger_test.go
Improve unit test coverage of restore package, part 2 of N.
Add unit tests (29% → 40%).
Performed some function extraction to allow for more focused testing. 
Tests 
- Unit test
Side effects
=> Add unit tests for 'restore.go' (TableRestore and chunkRestore)

cmd/tidb-lightning-ctl/main.go, cmd/tidb-lightning/main.go, lightning/common/util_test.go, lightning/config/config.go, lightning/config/config_test.go, lightning/config/configlist.go, lightning/config/configlist_test.go, lightning/config/global.go, lightning/lightning.go, lightning/lightning_test.go, tidb-lightning.toml
As a prerequisite of the "web interface", we'd like to have Lightning keep running even after import is finished. 
The behavior overlaps with a feature request which turns Lightning into a server, which we could submit tasks to it (similar to DM-master). The conversion is straightforward, so why not 🙃.
1. Split config into two classes: "Global config" and "Task config" (both  are subset of `tidb-lightning.toml`, unlike DM task settings). 
* Also refactored the existing argument parsing code to cut down the code duplication.
2. Added an HTTP endpoint which allows user to upload a Task config toml. 
3. Changed the public `Run()` method to loop for those uploaded tasks in server mode. Essentially like this:
```go
func Run() {
if !ServerMode {
run(globalConfig)
} else {
for taskConfig := …
```
=> config,lightning: Implements server mode 

tests/go.mod, web/go.mod
Currently when trying to import tidb-lightning externally on macOS we'll get a "malformed file path" error due to a `` ` `` in the filename of a test case. Since a Go module shouldn't need the integrated tests anyway, we just ignore these non-source folders instead of trying to fix Go 🤷.
Recommended in https://github.com/golang/go/wiki/Modules#can-an-additional-gomod-exclude-unnecessary-content-do-modules-have-the-equivalent-of-a-gitignore-file, we include an empty `go.mod` in the `tests/` and `web/` folder so they're no longer part of the Go module.
Tests 
- No code
Side effects
=> tests,web: exclude these directories from the Go module

lightning/restore/restore.go
Signed-off-by: Lonng <heng@lonng.org>
Fix the `initializeColumns` method.
=> lightning/restore: fix ColumnPermutation calculation

lightning/restore/restore.go, tests/concurrent-restore/config.toml, tests/concurrent-restore/run.sh
feedback from DBA, sometimes after import data successfully with lightning, `tikv_gc_life_time` remains `100h0m0s` and not recovers to the original value (often `10m0s`).
This is caused by concurrent execution of `restore table`, and the `tikv_gc_life_time` update timeline maybe intersect like following:
```
thread1:  get gc=10m ---> set gc=100h -----> checksum ------> rollback gc to 10m
thread2:  -------------------------------> get gc=100h -----> checksum -----> rollback gc to 100h
```
We query `tikv_gc_life_time` from downstream database before execution of restore table once
Tests 
- Unit test
=> restore: fix gc life time not recovered after table restore

cmd/tidb-lightning/main.go
Even if the log file failed to sync (usually caused by log file = /dev/stdout), it shouldn't cause the program to exit with failure.
Remove the condition that sync log fail causing exit(1).
Tests 
* Run the program
Side effects
- Need to cherry-pick to the release branch (2.1)
=> cmd: do not exit(1) if failed to sync log

lightning/backend/sql2kv.go, lightning/backend/sql2kv_test.go, lightning/restore/restore.go, tests/tool_1472/config.toml, tests/tool_1472/data/EE1472-schema-create.sql, tests/tool_1472/data/EE1472.notpk-schema.sql, tests/tool_1472/data/EE1472.notpk.1.sql, tests/tool_1472/data/EE1472.notpk.2.sql, tests/tool_1472/data/EE1472.pk-schema.sql, tests/tool_1472/data/EE1472.pk.1.sql, tests/tool_1472/data/EE1472.pk.2.sql, tests/tool_1472/run.sh
Fix #222 (= TOOL-1472). 
Remove the piece of code that pre-calculates the final AUTO_INCREMENT ID. Instead, let the encoder determines the actual value dynamically. This gives a tighter upper bound of the final AUTO_INCREMENT value and avoids overflowing AUTO_INCREMENT columns of shorter integer size (this doesn't work if PRIMARY KEY is not a handle column though, since `_tidb_rowid` will share the same AUTO_INCREMENT sequence)
Tests 
Side effects
=> backend: dynamically calculate the maximum auto-inc ID

lightning/checkpoints/checkpoints.go, lightning/checkpoints/checkpoints_test.go
fix empty map become nil after marshall and unmarshall
manually init these map. Seems it's a bug of marshall function provided by gogoproto.
Tests 
- Unit test, add an unit test. If we didn't init these map after unmarshall this test won't pass(hope I didn't make it wrong)
Side effects
=> checkpoint: fix empty map become nil after unmarshall

lightning/config/config.go, lightning/config/config_test.go, lightning/restore/restore.go
To reduce config of TiDB backend and user's effort, indexConcurrency and tableConcurrency may set to a large value automatically.
Computing the sum of tables to be imported, set indexConcurrency and tableConcurrency to this sum in TiDB backend mode
Tests 
- Unit test
Side effects
=> config: increase default concurrency

lightning/common/util.go, lightning/common/util_test.go, lightning/config/config.go, lightning/config/config_test.go, lightning/config/const.go, lightning/restore/tidb.go, tidb-lightning.toml
this allows sending rows > 4 MiB when using TiDB backend
Expose the [`maxAllowedPacket` DSN parameter](https://github.com/go-sql-driver/mysql/#maxallowedpacket) to `tidb-lightning.toml` (perhaps we should just accept arbitrary DSNs 🤷‍♂)
* Accept the `[tidb] max-allowed-packet = 67_108_864` config.
* When constructing the DSN to TiDB, include this value into the parameters.
Tests 
- Unit test
Side effects
- Need to update the documentation (document the new config)
- Need to update the `tidb-ansible` repository (add the new config to the templates)
- Need to be included in the release note (?)
=> config: adding `[tidb] max-allowed-packet` config

go.mod, go.sum, tests/go.mod, web/go.mod
Fix +incompatible suffix not allowed error reported by go mod
1. `go get -ugithub.com/pingcap/tidb@694e086e7`  (which is v3.0.4)
1. `go mod tidy`
Tests 
- Manual test
Use `make lightning` to check if we can still build.
- No code
=> Fix +incompatible suffix not allowed error reported by go mod

lightning/config/config.go, lightning/config/config_test.go, lightning/config/global.go
Previously it is not possible to supply the user password by command line, unlike other restore tools like `loader`
Adds `-tidb-password` command line option
Tests 
- Unit test
Side effects
=> Add password as command line argument

lightning/lightning.go, lightning/lightning_test.go
Fix #231. 
Implement `GET /tasks`, `GET /tasks/$id` and `DELETE /tasks/$id` even when the config list is nil.
Tests 
- Unit test
* run Lightning without server mode and access the web interface.
Side effects
=> lightning: ensure the web interface still works outside server mode

lightning/common/util.go, lightning/common/util_test.go, lightning/restore/restore.go, lightning/restore/restore_test.go, lightning/restore/tidb.go
Make sure the session param takes effect.
Set session var for every new conn. For every new connection created by the driver, it will set the params first.
Note the previous `setSessionConcurrencyVars` will set one connection
from the db connection pool, so we can't make sure the session will take
effect later using the `sql.DB`.
Tests 
- Unit test
check tidb log for the session params setted using the dsn.
Side effects
=> Make sure the session param takes effect

cmd/tidb-lightning-ctl/main.go, lightning/backend/tikv.go, lightning/backend/tikv_test.go
Fix #134 and AskTUG-33070.
1. During switch mode, if we encounter a store that returns Unimplemented (mainly TiFlash nowadays), simply ignore the error.
2. Added `./tidb-lightning-ctl --fetch-mode` subcommand to print the mode.
Tests 
- Unit test
Side effects
* Document the new `--fetch-mode` flag.
=> Some SwitchMode improvements

lightning/restore/checkreq_test.go, lightning/restore/restore.go
Signed-off-by: Tong Zhigao <tongzhigao@pingcap.com>
- Support store version format generated by `git describe --tags`, like `v4.1.0-alpha-9-ga27a7dd`.
Tests 
- Manual
=> Support store version format generated by `git describe --tags`

lightning/backend/tikv.go, lightning/mydump/region.go
https://github.com/pingcap/tidb-lightning/issues/309
Warn users when single table region size exceeds 1G.
Add warning log.
Tests 
- Unit test
=> Warn for single large file, change switch mode log level to info

lightning/restore/restore.go, tests/error_summary/run.sh
The suggested checkpoint error resolution command should be `--checkpoint-error-destroy=all`. Instead it was suggested to be `--checkpoint-errors-destroy=all`. There should be no `s`.
Tests 
Side effects
=> restore: fix a typo about the recommended action on checkpoint error.

lightning/lightning.go
Fix #231. 
Go serializes a nil slice into `null` rather than `[]`, which JavaScript will distinguish. 
Explicitly initialize the empty slice as `[]int64{}` to avoid this.
Tests 
* Run lightning outside the server mode and check the web page.
Side effects
=> lightning: fix web page not showing when not using server mode

cmd/tidb-lightning/main.go, lightning/config/global.go, lightning/log/log.go, tidb-lightning.toml
fix lightning always set log file path to the default path
Only set log path to default path if neither command line params nor config file set it 
Tests 
- Unit test
- No code
Side effects
=> log: fix log file path

lightning/backend/local.go
fix a divide by 0 bug in local backend when split index engine ranges
If the index engine total size is bigger than RegionSplitSize but small than indexCount * RegionSplitSize, thus each index range count will be 0, thus split kv-pairs by range will encounter divide by 0 panic.
Tests 
- Unit test
- No code
Side effects
=> backend: fix local backend may divide by 0

lightning/lightning.go
Add log for environment httpproxy settings
The default [connection dialer](https://github.com/grpc/grpc-go/blob/v1.26.x/clientconn.go#L200) will use the  httpproxy setting from environment variables (see [`httpproxy.FromEnvironment()`](https://github.com/golang/net/blob/master/http/httpproxy/proxy.go#L91-L98)) to setup connections. So log these environment variables can make it easier in trouble shooting.
Example log:
```
[2020/06/29 16:09:53.401 +08:00] [INFO] [lightning.go:242] ["environment variables"] [httpproxy="{\"HTTPProxy\":\"127.0.0.1:1080\",\"HTTPSProxy\":\"\",\"NoProxy\":\"\",\"CGI\":false}"]
```
Tests 
- Unit test
- No code
Side effects
- …
=> add log for environment http proxy setting

lightning/restore/restore.go
After https://github.com/pingcap/tidb/pull/18326 tidb won't always create all autoid allocators, so we should only update auto increment count when needed to avoid tidb panic.
Tests 
- Unit test
- No code
Side effects
=> post-process: only update auto increment id when needed

cmd/tidb-lightning/main.go, lightning/backend/local.go, lightning/lightning.go, lightning/lightning_test.go
Check process max open file limit for local backend
In local backend mode, pebble need to write a lot of L0 sst files. So If data source is fairly big, the max_open_file limit may not be enough. So we check the `RLIMIT_NOFILE` base on source file size, and try to update it if not big enough.
close #342 
Tests 
- Unit test
- No code
Side effects
=> server: check open file ulimit for local backend

lightning/backend/sql2kv.go, lightning/common/util.go, lightning/restore/restore.go
Do not rebase auto-id or generate row id column for table with common handle
Tests 
- Unit test
- No code
Side effects
=> restore: do not rebase auto-id or generate auto row id for table with common handle

cmd/tidb-lightning/main.go
When I run a new tidb-lightning task interactively, it generates a log file for verbose output. In my shell I double-click to pickup that file so I can copy it. Unfortunately it has a trailing `.` which is annoying enough to me that you are seeing this PR :-)
Message text change
- No code
Side effects
- None
- None
=> Fix verbose log message for shell

lightning/mydump/csv_parser.go, lightning/mydump/csv_parser_test.go, lightning/mydump/region.go, lightning/restore/restore.go
Enable csv parser to skip empty line. See: https://asktug.com/t/topic/36359/24
Csv parse will treat the first non-empty line as header instead of the first line. And will also skip empty lines.
Tests 
- Unit test
- No code
Side effects
Empty lines in CSV are ignored.
=> parser: fix csv parse header with empty line

lightning/checkpoints/checkpoints.go, lightning/checkpoints/checkpoints_sql_test.go, lightning/mydump/parser.go, lightning/restore/restore.go, lightning/restore/restore_test.go, tests/checkpoint_columns/config.toml, tests/checkpoint_columns/run.sh
Fix missing column infos when restore from checkpoint
- Write Chunk ColumnPermutation to checkpoint db (file/mysql)  when insert or update chunk checkpoints.
- When restore from checkpoint, also restore column infos for parser from stored  `ColumnPermutation`
NOTE: this fix can't handle following case:
table schema:
```
create table t(a varchar(32), b int);
```
data.sql
```
insert into t (a, b) values 
("test1", 1),
("test2", 2);
insert into t (a) values 
("test3"),
("test4");
```
If multi insert statements contains different columns number for their order are different, Mable recover from checkpoint will still fail because we don't update columns infos on the fly. 
Tests 
- Unit test
- No code
Side effects
Related …
=> restore: fix missing colum infos when restore from checkpoint

lightning/backend/backend.go
Before this commit we use unix timestamp as commit ts for each kv pair in tikv. 
And when we want use commits as filter(e.g. difference backup with BR), this would filter wrong result.
so I think we should encode all commit ts as pd tso.
use compose to encode commit ts.
Tests 
before this commit(local and importer backend are same):
after this commit(local and importer backend are same):
=> backend: use pd tso as commit ts in local and importer backend

lightning/backend/tidb.go, lightning/backend/tidb_test.go
close #205
if set sql-mode to strict mode, will check each string value by `table.CastValue`
Tests 
- Unit test
- No code
Side effects
=> encoder: check string value for tidb encoder

tests/run.sh
Currently, when we exec `TEST_NAME=... tests/run.sh`,  this will actually run all tests that name start with `TEST_NAME`. 
This pr change the meaning for `TEST_NAME` to contain one or more  test case name, and the script will only run these cases. By these way we can control the concurrency to exec the test cases. 
After this change, we can update our ci script to run integration test in parallel, see this example: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/lightning_ghpr_test/detail/lightning_ghpr_test/1507/pipeline/53
Tests 
- Unit test
- No code
Side effects
- Change the meaning of `TEST_NAME`, so if some job depend on this, they may fail.
=> test: change integration test script to allow run tests in parallel

lightning/restore/restore.go
Fix the bug that if lightning exit before finished, e.g. manually cancelled, some checkpoint update may not be written to db before exit.
We have encounter this bug several times in recent integration test's failure. Example:  https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/lightning_ghpr_test/detail/lightning_ghpr_test/1570/pipeline/47/
If lightning exit early, wait for checkpoint finish before exit.
Tests 
- Unit test
- No code
Side effects
=> checkpoint: wait checkpoint finished if exit before success

lightning/backend/local.go, tests/README.md, tests/_utils/check_cluster_version, tests/run.sh, tests/tiflash/config.toml, tests/tiflash/run.sh
close #391 
Use `store.GetPeerAddress` as the address to open gRPC connect and add a integration test for tiflash
Tests 
- Unit test
- No code
Side effects
=> backend: use peer address as grpc addr for tiflash store

go.mod, go.sum, lightning/checkpoints/checkpoints.go, lightning/checkpoints/checkpoints_sql_test.go, tests/source_linkfile/config.toml, tests/source_linkfile/run.sh
- update to newest br to fix WalkDir bug for soft link files, see: https://github.com/pingcap/br/pull/492
- Also move task checkpoint table to the backup db when backup checkpoint db
Tests 
- Unit test
- No code
Side effects
=> loader: fix store.WalkDir return inaccurate file size for soft link source files

lightning/restore/restore.go
Fix chunk checkpoint `row_id` and `offset` maybe occasionally reset if chunk remain rows are empty.
Giving a sql source file: 
```
insert into a values (2);
```
And It's initial chunk checkpoint:
```
Chunk{Offset:0, EndOffset: 25, PrevRowIDMax: 8, RowIDMax:16}
```
After read the only first row, the checkpoint will be updated to:
```
Chunk{Offset:24, EndOffset: 25, PrevRowIDMax: 9, RowIDMax:16}
```
If lightning exit at this point and restart with checkpoint, then since this check offset < EndOffset , lightning will restore this chunk again, but there is no more row, so the checkpoint will be update as:
```
Chunk{Offset:0, EndOffset: 25, PrevRowIDMax: 0, RowIDMax:16}
```
By the current logic: https://github.com/pingcap/tidb-lightning/blob/6e39bb857e2d728c2eb676fbf4739d1f83b6a94d/lightning/re …
=> checkpoint: fix chunk checkpoint may reset offset and row id

tests/checkpoint_error_destroy/file.toml, tests/checkpoint_error_destroy/run.sh, tests/common_handle/run.sh, tests/file_routing/run.sh
- Skip run test `file-routing` with local backend when verion < v4.0.0
- Run integration test `common_handle` for all 3 backend
- fix a occasional test failure for `checkpoint_error_destroy` do to remain checkpoint file by other test.  see: https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/lightning_ghpr_test/detail/lightning_ghpr_test/1720/pipeline/
close #388
Tests 
- Unit test
- No code
Side effects
=> test: fix integration test for 3.x version

tests/README.md, tests/run.sh, tests/source_linkfile/run.sh, tests/tiflash/run.sh
Make TiFlash optional, so we can avoid trying to start tiflash with v3.0.0 tidb cluster
After this change, we need to add `TIFLASH=1` environment when run with v3.1 or upper cluster
Tests 
- Unit test
- No code
Side effects
=> test: make start tiflash optional in integration test

lightning/config/config.go, lightning/config/config_test.go, lightning/config/global.go, lightning/restore/restore.go, tidb-lightning.toml
add optional level for post-restore operations close #403.
Add operation level: 'off', 'optional', 'required' for post-restore operations checksum and analyze.
Tests 
- Unit test
- No code
Side effects
Release Note
- Add an intermediate "optional" level for post-restore operations
=> post-restore: add optional level for post-restore operations

lightning/backend/local.go, lightning/backend/local_test.go
- add retry for `SplitAndScatterRegionByRanges` since it may caused by region leader changes
- do not directly retry ingest if the return error is `EpochNotMatch` because tikv will check the epoch in SstMeta and the newest Region info, but we can change the epoch in SstMeta 
- retry ingest if the error is `Raft raft: proposal dropped`, because this means there is a leader transfer for this region
- downgrade some log level from Error to Warn, since they are retryable
- fix a bug in backend/log that cause scan region by range return one more region that does not intersect with the range  if the range end key is prefix of the region start key
Tests 
- Unit test
- No code
Side effects
Release Note
- fix …
=> backend/local: do not retry epochNotMatch error when ingest sst

lightning/backend/local.go, lightning/backend/localhelper.go
- Simplify some error and warn log. Downgrade the log level or change zap.Error to log.ShortError to make log more user friendly
- When ingesting returns epoch-not-match error, if the range still in the new region, we should retry from writing kv-pairs instead of directly return an error. The updated logic should be the same as current tikv-import implementation
Tests 
- Unit test
- No code
Side effects
=> log: simplify some warn log and do retry write for epoch not match error

tests/_utils/run_services, tests/row-format-v2/run.sh
When investigating the test failure in #420, I found if we run 'new_collation row-format-v2 various_types' these three tests together, the last test will fail stably. 
Tests 
- Unit test
- manual test (run TEST_NAME='new_collation row-format-v2 various_types' tests/run.sh)
Side effects
=> test: fix a unstable integration test

lightning/config/config.go, lightning/config/config_test.go
currently in lightning via SQL, task config is encoded to string and write to `GlobalConfig.ConfigFileContent`. (I'll add a better interface later). `PostOpLevel` and `Duration` are different from their input format after encoding.
add `MarshalText` to these struct
Tests 
- Unit test
Side effects
=> config: support encode PostOpLevel and Duration as input

Makefile, cmd/tidb-lightning-ctl/main.go, go.mod1, go.sum1, lightning/backend/backend.go, lightning/backend/backend_test.go, lightning/backend/importer.go, lightning/backend/importer_test.go, lightning/backend/local.go, lightning/backend/tidb.go, lightning/restore/restore_test.go, mock/backend.go, tools/go.sum
after hiding lighting's go.mod and embedded it into tidb, an error checkpoint tool will raise error like
```
$ ./tools/check/check-errdoc.sh
Generate errors.toml failed: exit status 2, output:
../../../../pkg/mod/github.com/pingcap/tidb-lightning@v4.0.9-0.20201104053247-8013216a3446+incompatible/lightning/backend/local.go:486:26: multiple-value uuid.NewV4() in single-value context
```
update satori/go.uuid to latest
Tests 
- pass original test
Side effects
=> dep: update uuid dependency to latest google/uuid

cmd/tidb-lightning-ctl/main.go, lightning/config/config.go
Since #361 there is a check if the data source actually exists. This breaks `tidb-lightning-ctl` which does not require the data source directory.
Change the default `-d` in `tidb-lightning-ctl` from empty string to `noop://`. 
Also added `noop` to the supported protocol list.
Tests 
* --fetch-mode works without passing `-d`.
Side effects
=> tidb-lightning-ctl: change default of -d to 'noop://'

lightning/common/util.go, lightning/common/util_test.go, lightning/config/config.go, lightning/config/config_test.go, lightning/config/global.go, tidb-lightning.toml
If the data source contains system schemas, they may be accidentally get imported and corrupt the cluster.
Explicitly filter out system schemas (`mysql.*`, etc.) like pingcap/dumpling#194
Tests 
- Unit test
Side effects
* System schemas like `mysql.*` are excluded by default. Use `-f '*.*'` to explicitly include them.
=> config: filter out all system schemas by default

lightning/config/config.go, lightning/config/config_test.go, lightning/mydump/router.go, lightning/mydump/router_test.go
- Add checksum for file routing `pattern` and `path` both empty
- Allow absolute path for `mydumper.files.path`, convert it to the relative path at `config.Adjust`
close #469 
Tests 
- Unit test
- No code
Side effects
=> mydumper: verify file routing config

Makefile, go.mod1, lightning/config/bytesize.go, lightning/config/bytesize_test.go, lightning/config/config.go, lightning/config/const.go, lightning/mydump/csv_parser_test.go, lightning/mydump/parser_test.go, lightning/mydump/region.go, lightning/mydump/region_test.go, lightning/restore/checksum_test.go, lightning/restore/restore.go, tidb-lightning.toml
Several config specifies a large byte size, which is not very readable (and some DBAs are still unfamiliar with the underscore-as-number-separator TOML feature).
Using [`docker/go-units`](https://pkg.go.dev/github.com/docker/go-units) (already used by Dumpling and PD), we support parsing human-readable byte size for the following config:
* tikv-importer.region-split-size (100_663_296 → '96 MiB')
* mydumper.read-block-size (65536 → '64 KiB')
* mydumper.batch-size (107_374_182_400 → '100 GiB')
* mydumper.max-region-size (268_435_456 → '256 MiB')
Byte size can be specified using integers (`65536` or `65_536`, backward-compatible with existing config), floating point (`6.5536e+4`), or a string involving byte units (`'64k'`, `'64 K'`, `'64KiB'`, `'64 kb'`, `'0.0625 MB'`, all equivalent).
(This …
=> config: allow four byte-size config to be specified using human-readable units ("100 GiB")

cmd/tidb-lightning-ctl/main.go, lightning/backend/backend.go, lightning/backend/checkreq_test.go, lightning/backend/importer.go, lightning/backend/local.go, lightning/backend/tidb.go, lightning/backend/tikv.go, lightning/common/security.go, lightning/common/security_test.go, lightning/common/util.go, lightning/common/util_test.go, lightning/common/version.go, lightning/config/config.go, lightning/config/config_test.go, lightning/lightning.go, lightning/restore/checksum.go, lightning/restore/restore.go, mock/backend.go
Replace some usage of `context.Backend` or `context.TODO` with lightning app context. So we can stop some sub task more quickly.
close #462 
Tests 
- Unit test
- No code
Side effects
=> *: replace context.Backend with app context

lightning/mydump/parquet_parser.go, lightning/mydump/parquet_parser_test.go, tests/checkpoint_parquet/parquet.go, tests/checkpoint_parquet/run.sh
Convert parquet reader columns to lower case to be compatible with other logics involving the column names
close #480 
Tests 
- Unit test
- No code
Side effects
=> mydumper: convert parquet columns to lower case

tests/column_permutation/data/perm.test_perm-schema.sql
Fix an integration test that failed to create table with:
```
[2020-11-25T06:33:57.764Z] [2020/11/25 14:33:56.121 +08:00] [WARN] [session.go:1245] ["run statement failed"] [conn=6688656886226485375] [schemaVersion=78] [error="[types:1406]Data Too Long, field len 8, data len 19"] [session="{\n  \"currDBName\": \"\",\n  \"id\": 6688656886226485375,\n  \"status\": 2,\n  \"strictMode\": false,\n  \"user\": {\n    \"Username\": \"root\",\n    \"Hostname\": \"127.0.0.1\",\n    \"CurrentUser\": false,\n    \"AuthUsername\": \"root\",\n    \"AuthHostname\": \"%\"\n  }\n}"]
[2020-11-25T06:33:57.764Z] [2020/11/25 14:33:56.121 +08:00] [INFO] [conn.go:801] ["command dispatched failed"] [conn=6688656886226485375] [connInfo="id:6688656886226485375, addr:127.0.0.1:53080 status:10, …
```
=> test: fix an unstable integration test

tests/_utils/run_services
Fix test failure due to can't restart tiflash
The newest tiflash process is "TiFlashMain", so use `killall tiflash` cannot kill it.
```
ps aux |grep tiflash
root      12530 15.5  0.8 3316776 1714152 pts/4 Sl   11:23   0:10 bin/tiflash server --config-file=/tmp/lightning_test_result/tiflash.toml
ps -p 12530 -o comm=
TiFlashMain
```
Tests 
- Unit test
- No code
Side effects
=> test: fix can not kill tiflash process by name

lightning/backend/backend.go, lightning/backend/backend_test.go, lightning/backend/importer.go, lightning/backend/local.go, lightning/backend/session.go, lightning/backend/sql2kv.go, lightning/backend/sql2kv_test.go, lightning/backend/tidb.go, lightning/backend/tidb_test.go, lightning/restore/restore.go, lightning/restore/restore_test.go, mock/backend.go, tests/_utils/run_sql, tests/generated_columns/data/gencol-schema-create.sql, tests/generated_columns/data/gencol.nested-schema.sql, tests/generated_columns/data/gencol.nested.0.sql, tests/generated_columns/data/gencol.various_types-schema.sql, tests/generated_columns/data/gencol.various_types.0.sql, tests/generated_columns/run.sh, tests/restore/run.sh
Properly support stored generated columns in local/importer backends.
Unlike virtual generated columns, the value of stored generated columns are saved into the KV entries. This is computed before `AddRecord()`. Therefore, before this PR, all stored generated columns imported using local or importer backends become NULL.
We now fill in the stored generated columns by evaluating their expressions. 
Tests 
Side effects
Fixed: In local and importer backends, stored generated columns are properly filled in instead of being NULL.
=> backend: support stored generated columns in local/importer backends

lightning/backend/backend_test.go, lightning/backend/session.go, lightning/backend/session_test.go, lightning/backend/sql2kv.go, lightning/backend/sql2kv_test.go, lightning/backend/tidb_test.go, lightning/glue/glue.go, lightning/restore/restore.go, lightning/restore/restore_test.go, lightning/restore/tidb.go, lightning/restore/tidb_test.go, tests/_utils/read_result, tests/auto_random_default/run.sh, tests/generated_columns/data/gencol.various_types-schema.sql, tests/generated_columns/run.sh
Fix #504.
Copy all sys vars that affects expression evaluation results in additional to `tidb_row_format_version`.
Tests 
- Unit test
- Integration test (will add integration test after #505 is merged)
Side effects
=> backend,restore: duplicate more important system variables from downstream

lightning/backend/local.go, lightning/backend/local_unix.go, lightning/backend/local_windows.go, lightning/lightning.go, lightning/lightning_test.go, lightning/restore/restore.go
Set the maximum open file limit for pebble to avoid open files exceeds the system open files limit
- set the estimated max open files limit to (sum of topN table files size) / tableConcurrency * 2
- check the estimated open files limit with a default min value of 1024. 
- Set pebble maxOpenFiles to the estimatedOpenFiles, L0CompactionThreshold and L0StopWritesThreshold to estimatedOpenFiles/2.
Tests 
- Unit test
- No code
Side effects
- Since if there are more files in pebble than estimatedOpenFiles/2, pebble will start compacting L0 SST files and stop write, thus there may be performance regression in some extreme condition
=> backend/local: set pebble db max file limit

lightning/backend/local.go, lightning/backend/local_test.go, tests/various_types/data/vt.precise_types-schema.sql, tests/various_types/run.sh
in tikv release-4.0, tikv will force truncate all row keys, so our currently truncate key is not valid according to this logic. 
See: https://github.com/tikv/tikv/blob/f7f22f70e1585d7ca38a59ea30e774949160c3e8/components/raftstore/src/coprocessor/split_observer.rs#L36-L41
If the key is a row key, use handle.Next() to generate the next key, else, append a 0x00 to the key otherwise.
Tests 
- Unit test
- No code
Side effects
=> backend/local: fix next key

lightning/backend/sql2kv.go, lightning/restore/restore.go
close https://github.com/pingcap/tidb/issues/21342
planner/core and expression package need to be imported together to initialized expression.RewriteAstExpr
Tests 
- Unit test
- No code
Side effects
=> backend: import planner/core package to initialize expression.RewriteAstExpr

lightning/backend/localhelper.go, lightning/backend/localhelper_test.go
Fix the bug that the retry split key is not encoded, which causes scanned regions are incorrect.
- Fix the retry split scan keys bug 
- Add more error checks and logs
- Add some unit tests
Tests 
- Unit test
- No code
Side effects
Release Note
- Fix the bug that the retry scan region key is not encoded, which causes the retryed region is not split.
=> backend/local: add encode for retry scan region keys

lightning/restore/tidb.go, lightning/restore/tidb_test.go
Fix https://github.com/pingcap/tidb/issues/21827
break create loop immediately when error encountered
Tests 
Release note:
- Fix the issue that lost create table error during multiple tables created.
=> restore: fix error lost in create schema

go.mod1, go.sum1
Update to newest br to apply https://github.com/pingcap/br/pull/618
Tests 
- Unit test
- No code
Side effects
=> mydumper: update br to apply auto retry s3 read error

lightning/restore/checksum.go, lightning/restore/restore.go
after use lightning as library, `init()` changed TiDB's global configuration unexpected
try removing usage of tidbcfg
Tests 
- pass original test
Side effects
=> restore: don't change TiDB config to support lightning via SQL

lightning/config/config.go, lightning/config/global.go, lightning/lightning.go, lightning/log/log.go, tidb-lightning.toml
In https://github.com/pingcap/tidb-lightning/pull/538, we added the `redact-log` parameter.
The redact log parameter name is different from TiKV's and PD's.
https://github.com/tikv/tikv/blob/master/etc/config-template.toml#L846
In TiKV it's `redact-info-log` configuration in config file.
https://github.com/tikv/pd/blob/master/server/config/config.go#L1373
In PD it's `redact-info-log` configuration in config file.
Change `redact-log` to `redact-info-log`.
Tests 
- Unit test
Side effects
=> config: change redact log parameter name

lightning/backend/local_test.go, lightning/backend/tidb.go, lightning/backend/tidb_test.go
#378 added string value check in tidb backend if the SQL mode is strict. But this causes #550  because tidb backend doesn't fetch the full table meta which causes CastValue panic. 
Disable this feature before we come up with a correct solution.
Tests 
- Unit test
- No code
Side effects
=> backend/tidb: temporarily disable the strict-mode value check in tidb backend 

metrics/grafana/lightning.json
Many users(come from DBaaS、operator、tiup) monitor multiple TiDB clusters in one Grafana, this PR make Grafana dashboards support multiple clusters and not affect single cluster usage. Cluster variable is hidden by default.
- add a tidb_cluster label in all expr
- add cluster variable in Grafana templating
How it Works:
load it to your Grafana :))
Single Cluster:
No change
Multiple Cluster:
Construct a label that can uniquely identify the cluster. in tidb_operator, you can use {namespace}-{cluster_name} as your {tidb_cluster} variable.
add this configuration to your prometheus config
```
relabel_configs:
- source_labels:
- namespace
- name
separator: "-"
target_label: tidb_cluster
```
Tests 
- No code
Side effects
- No effects
- https://github.com/pingcap/tidb/pull/22503
- …
=> grafana dashboards support multiple cluster

metrics/grafana/lightning.json
Signed-off-by: zhengjiajin <zhengjiajin@pingcap.com>
The latest version of tidb-operator will use the instance name as the cluster label. The previous expression uses the cluster label got the value of the tidb_cluster variable. It will cause Grafana can not to display the data.
Tests 
- No code
Side effects
- No effects
- https://github.com/pingcap/tidb/pull/22557
=> metrics: use tidb_cluster label get variable values

tests/_utils/run_services
Use different CA common name to avoid tikv SSL verification failed.
Tests 
Side effects
=> test: fix ssl key ca name
