Makefile

Tests 
- Unit test
- No code
Side effects

add coverage report

---

README.md

add code coverage badge and build status
add code coverage badge and build status
Tests 
- Unit test
- No code

add code coverage badge and build status

---

lightning/restore/restore.go

Index engine worker will be released after `TableRestore.postProcess` in the current implementation, and `TableRestore.postProcess` contains `checksum` and `analyze` steps which should not keep index worker.
Extract the table restore engines logic to an individual method, and eager release index engine worker after all data engines and index engine were been imported.
Tests 
Side effects
N/A
N/A

restore: eager release index engine worker after imported

---

lightning/restore/restore.go

This reverts commit 852c5e954877692035efe5c3e44ddcf8f915d90b.
lightning meets `segmentation violation` error, we revert the related pr firstly, #145  would change the pipeline mode

Revert "fix deadlock and goroutine leak in chunk restore (#149)"

---

Makefile

cherry pick #180 
Tests 
- Unit test

[2.1] Cherry-pick #180

---

lightning/common/util_test.go
lightning/common/version_test.go
lightning/log/log.go

Signed-off-by: Lonng <chris@lonng.org>
Improve unit test coverage of 'common' package

common: improve unit test coverage of 'common' package

---

lightning/config/config_test.go
lightning/lightning_test.go
lightning/log/log.go
lightning/log/log_test.go
lightning/metric/metric_test.go
lightning/worker/worker_test.go

Signed-off-by: Lonng <chris@lonng.org>
Improve unit test coverage of 'lightning' package

lightning: improve unit test coverage of 'lightning' package

---

README.md

README: update coverage status badge

README: update coverage status badge

---

lightning/config/config_test.go

Signed-off-by: Lonng <chris@lonng.org>
Add unit test for package `config` (86% → 99.1%)

config: improve unit test coverage of 'config' package

---

tidb-lightning.toml

The description of level-1-compact, compact has some mistakes in lightning.toml. 
Fix the mistake in lightning.toml and update the default value of `compact` config.  

Post restore config fix

---

tidb-lightning.toml

* fix the mistake in lightning config file
* fix typo
* remove the "also" in description
Tests 
- No code
Side effects

[2.1] Cherry-pick #202

---

lightning/restore/restore.go

Signed-off-by: Lonng <heng@lonng.org>
Cherry-pick #210 for release-3.0

lightning/restore: fix ColumnPermutation calculation

---

lightning/restore/restore.go
tests/concurrent-restore/config.toml
tests/concurrent-restore/run.sh

Cherry-pick #218 to release-2.1.
Tests 
- Unit test
Side effects

restore: fix gc life time not recovered after table restore (#218)

---

lightning/common/util_test.go

improve the unit test coverage
add unit test for util in common, improve unit test coverage from 56% to 82%
Tests 
- Unit test

lightning/common: add unit test

---

go.mod
go.sum
mock/importer.go

Fit interface with [tikv/importer#17](https://github.com/tikv/importer/pull/17)
Use `mockgen` to generate latest gRPC mock files.
Tests 
- Unit test
Side effects

mock: update rpc endpoint

---

lightning/restore/checkpoint_test.go
lightning/restore/checkpoints.go

cherry-pick for #237
Tests 
- Unit test
Side effects

[2.1]checkpoint: fix empty map become nil after unmarshall (#237)

---

lightning/config/global.go
lightning/restore/restore.go
lightning/restore/tidb.go
tests/error_summary/config.toml
tests/error_summary/run.sh
tidb-lightning.toml

Tests 
- Unit test
- No code
Side effects

improve the log when encountering invalid checkpoint

---

metrics/alertmanager/lightning.rules.yml
metrics/grafana/lightning.json

Copy the Grafana board from `tidb-ansible` into this repository.
Tests 
- No code
Side effects

metrics: copy the grafana board into this repo

---

lightning/backend/session.go
lightning/backend/sql2kv_test.go

In pingcap/tidb#12466 the `LightningMode` session variable was removed. One side effect is that a new 4 KB `BufStore` was initialized for every call to `AddRecord()`, which incurs 9% of the `Encode()` run time.
This PR constructs a dummy `BufStore` which forwards all writes to the transaction directly, similar to how `LightningMode` was implemented. 
<details><summary>Flamegraphs of the benchmark function against the TPC-C CUSTOMER table</summary>
Before: ![encode-only-profile-before-fs8](https://user-images.githubusercontent.com/103023/75565740-78af5f80-5a89-11ea-9fc3-9da666f9c890.png)
After: 
</details>
Tests 
- Unit test
Side effects

backend: define a dummy BufStore when creating a new session

---

README.md

The old url is not aviliable. This PR updates the url of the Chinese document.

Update Chinese doc url

---

go.mod
go.sum

update tidb-tools to solve table name changing after applyOn black-white-list, details at https://github.com/pingcap/tidb-tools/pull/342
change tidb-tools to latest version
Tests 
- No code

update tidb-tools to latest

---

lightning/lightning.go
lightning/restore/restore.go

close #335 
Wait checkpoint routine finish before cleanup checkpoints.
Tests 
- Unit test
- No code
Side effects

wait checkpoint routine finish before cleanup

---

lightning/backend/tidb.go

close #355 
Add an error log when tidb backend execute sql statement failed
Tests 
- Unit test
- No code
Side effects

backend/tidb: add log when execute statement failed

---

tests/run.sh

add some config for pd and tiflash to make tiflash integration test run more stable.
Tests 
- Unit test
- No code
Side effects

make tiflash test more stable

---

lightning/backend/tidb.go
lightning/backend/tidb_test.go

Fix the compatible issue in `show table t next_row_id` with v4.0.0~ v4.0.2
In v4.0.0 tidb  `show table t next_row_id` don't return the `ID_TYPE ` column, so we should Scan by column count and set the default value without the extra row
Tests 
- Unit test
- No code
Side effects

backend/tidb: fix compatible issue in fetch table schemas 

---

go.mod1
go.sum1

Update dependency `parquet-go` to include https://github.com/xitongsys/parquet-go/pull/330
close #442 
Tests 
- Unit test
- No code
Side effects

mydumper: fix s3 parquet reader

---

lightning/restore/checksum.go
lightning/restore/checksum_test.go

Tests 
- Unit test
- No code
Side effects

restore: fix service gc id don't take effect

---

tests/various_types/data/vt.double-schema.sql

close #473 
change `DOUBLE(16)` to `DOUBLE`
Tests 
Side effects

test: change double type syntax

---

lightning/backend/local.go
lightning/backend/localhelper.go
lightning/lightning.go
lightning/lightning_test.go
lightning/mydump/loader.go
lightning/mydump/loader_test.go
lightning/restore/restore.go

- Add some error description to make the error log clearer
- avoid retrying `context. Canceled` error
close #513
Tests 
- Unit test
- No code
Side effects
Release Note
- Add some error description to make the error log clearer

*: add some error description

---

tests/auto_random_default/run.sh

fix unstable integration test `auto_random_default` by skip check total auto_random prefix with tidb backend.
Tests 
- Unit test
- No code
Side effects

test: fix unstable integration test auto_random_default

---

lightning/config/config.go
lightning/config/global.go
lightning/lightning.go
lightning/log/log.go
tidb-lightning.toml

cherry-pick #547 to release-4.0
Tests 
- Unit test
- No code
Side effects

config: change redact log parameter name (#547)

---

tests/s3/config.toml
tests/s3/run.sh

Fix s3 integration test by setting the source dir to the right s3 address.
Tests 
- Unit test
- No code
Side effects

test: fix s3 integration test

---

README.md

*: fix lightning arch image address
